openapi: "3.0.0"
info:
  version: 1.0.0
  title: Premdiction... the Premier League Prediction App
paths:
  /:
    get:
      summary: Home page.
      responses:
        '200':
          description: Welcome message.

  /register:
    post:
      summary: Registers a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        '200':
          description: New user registered.
        '400':
          description: Bad request.

  /login:
    post:
      summary: Logs in a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: User logged in successfully.
        '400':
          description: Bad request.
        '401':
          description: Login failed.

  /predictions:
    post:
      summary: Creates a new prediction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Prediction'
      responses:
        '200':
          description: Prediction created.
        '400':
          description: Bad request.
    get:
      summary: Gets all predictions.
      responses:
        '200':
          description: Lists all predictions.

  /predictions/{id}:
    put:
      summary: Updates a prediction.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Prediction'
      responses:
        '200':
          description: Prediction updated.
        '400':
          description: Bad request.
    delete:
      summary: Deletes a prediction.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Prediction deleted.

  /matches/{id}:
    put:
      summary: Updates a match.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Match'
      responses:
        '200':
          description: Match updated.
        '400':
          description: Bad request.

  /users/high_scores:
    get:
      summary: Retrieves the highest scores.
      responses:
        '200':
          description: Lists users with the highest scores.

  /users/{id}:
    get:
      summary: Retrieves information about a specific user.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User information.

  /matches:
    get:
      summary: Retrieves all matches.
      responses:
        '200':
          description: Lists all matches.

  /teams:
    get:
      summary: Retrieves all teams.
      responses:
        '200':
          description: Lists all teams.

  /teams/{id}/players:
    get:
      summary: Retrieves all players in a team.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lists all players in a team.

  /players:
    get:
      summary: Retrieves all players.
      responses:
        '200':
          description: Lists all players.

  /players/{id}:
    get:
      summary: Retrieves a specific player.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Player information.

components:
  schemas:
    Register:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    Login:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

    Prediction:
      type: object
      properties:
        user_id:
          type: string
        match_id:
          type: string
        result:
          type: string

    Match:
      type: object
      properties:
        home_team_id:
          type: integer
        away_team_id:
          type: integer
        home_score:
          type: integer
        away_score:
          type: integer
        date:
          type: string
          format: date-time

